In [1]:
import numpy as np
import pandas as pd
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [2]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [3]:
row1 = a[1,:]
row1
row2 = a[2,:]
row2
row1.shape

(4,)

In [10]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
# print(x.dot(y))
print(np.sum(x))
print(np.sum(x, axis = 1))
print(y.T)


10
[3 7]
[[5 7]
 [6 8]]


In [16]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vvvv  = np.tile(v,(4,1))
vvvv + x

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [17]:
from scipy.misc import imread,imsave,imresize